シフト申請時のバグ修正
ayumi0201/shift-app pull request #3
Opened 2022-07-09 06:17 UTC by ayumi0201

## このプルリクエストで何をしたのか
- シフト申請時にスケジュール登録が機能していなかったため修正
- 原因はbootstrap導入時にフォームタグが変更されたため。
## 追加した開発手順
[開発手順リスト](https://www.notion.so/dcd4f58fc1db43eab6f4d3d12d0ac645)

## 重点的に見てほしいところ(不安なところ)

## 実装できなくて後回しにしたところ

## 解決できなかったrubocop指摘

## チェックリスト
- [ ] 動作確認は実行した?
- [ ] rubocopは実行した?

## その他参考情報
- 実装する上で参考にしたサイトなどがあればリンクをここに貼ること

2022-07-09 06:24 UTC, yuki-tachi0219 requested changes

2022-07-09 06:24 UTC, yuki-tachi0219 commented on app/controllers/employee/attendance_requests_controller.rb
> +    binding.pry
↑

2022-07-09 06:57 UTC, ayumi0201 commented on app/controllers/employee/attendance_requests_controller.rb
> +    binding.pry
@yuki-tachi0219 
申し訳ございません。削除しました。
https://github.com/ayumi0201/shift-app/pull/3/commits/152f4a26163f39d1f2c9ed53b84283b02079d958

2022-07-10 05:18 UTC, yuki-tachi0219 approved these changes
LGTM!

2022-07-10 05:56 UTC, merged